test fail

diff --git a/.github/workflows/report-workflow.yml b/.github/workflows/report-workflow.yml
--- a/.github/workflows/report-workflow.yml
+++ b/.github/workflows/report-workflow.yml
@@ -14,14 +14,15 @@ jobs:
       - name: Generate random status
         id: random
         run: |
-          # Randomly generate 0 or 1
-          RANDOM_NUM=$(( $RANDOM % 2 ))
-          if [ $RANDOM_NUM -eq 0 ]; then
-            echo "status=failed" >> $GITHUB_OUTPUT
-            exit 1
-          else
-            echo "status=passed" >> $GITHUB_OUTPUT
-          fi
+          exit 1
+          # # Randomly generate 0 or 1
+          # RANDOM_NUM=$(( $RANDOM % 2 ))
+          # if [ $RANDOM_NUM -eq 0 ]; then
+          #   echo "status=failed" >> $GITHUB_OUTPUT
+          #   exit 1
+          # else
+          #   echo "status=passed" >> $GITHUB_OUTPUT
+          # fi
 
   run-ui-tests:
     needs: random-check
